= Kubernetes ConfigMap ConfigSource Example

* goal
    ** access -- , via `FileSystemConfigSource`, to -- a Kubernetes ConfigMap configuration

== Setup

* dependency / read Kubernetes ConfigMap configuration
    ** Reason: 🧠`FileSystemConfigSource` is implemented | `SmallRyeConfig` module🧠
+
[source,xml,subs="verbatim,attributes"]
----
<dependency>
    <groupId>io.smallrye.config</groupId>
    <artifactId>smallrye-config-source-file-system</artifactId>
    <version>{version}</version>
</dependency>
----

== Registration

The `smallrye-config-source-file-system` automatically registers a `FileSystemConfigSourceFactory` that accepts the
configuration property `smallrye.config.source.file.location` to set the volume path and read the Kubernetes ConfigMap.

Usually, an environment variable `SMALLRYE_CONFIG_SOURCE_FILE_LOCATION` sets the ConfigMap location in the Kubernetes
file descriptor.

== Run

* goal
    ** starts a http server / 1! endpoint: `/configMap`
    ** deploy the example | Kubernetes cluster

* steps
    ** set up a local Docker Registry
        *** Reason:🧠store the generated Docker images🧠
+
[source,bash]
----
docker run -d -p 5000:5000 --restart=always --name docker-registry registry:2
----
    ** set up a host | '/etc/hosts' / point `127.0.0.1` -- to -- `docker-registry`
    ** | link:../../[root path]
        *** `mvn clean install`
    ** build the example
+
[source,bash]
----
mvn package docker:build docker:push
----
        *** Problems:
            **** Problem1: "[ERROR] DOCKER> Unable to pull 'adoptopenjdk/openjdk11:alpine-slim' from registry 'docker.io"
                ***** Solution: TODO:
    ** deploy to Kubernetes
+
[source,bash]
----
kubectl apply -f .kubernetes
----

    ** hit link:sample.http[sample]
